-- =====================================================================
-- Mr. Brown CRM — esquema do banco (Supabase / Postgres)
-- =====================================================================
-- Como usar: painel do Supabase → SQL Editor → New query → cole tudo → Run.
-- O script é IDEMPOTENTE: pode ser executado quantas vezes quiser sem
-- duplicar nada (create ... if not exists / create or replace / drop+create
-- de triggers e políticas / insert ... on conflict do nothing).
--
-- Resumo do que ele cria:
--   1. Tabelas usuarios, contatos, produtos, pedidos, pedido_itens
--   2. Triggers auxiliares (atualizado_em, normalização de e-mail)
--   3. Funções usuario_atual(), usuario_ativo(), eh_admin()
--   4. Triggers em auth.users que restringem o cadastro a e-mails conhecidos
--   5. RLS (segurança por linha) em todas as tabelas
--   6. Permissões (grants) para o papel "authenticated"
--   7. Publicação realtime das 5 tabelas
--   8. Seed: 3 usuários iniciais + 7 produtos do site
-- =====================================================================


-- ---------------------------------------------------------------------
-- 0. Extensões
-- ---------------------------------------------------------------------
-- gen_random_uuid() já vem no Postgres 13+, mas garantimos a extensão.
create extension if not exists pgcrypto;


-- ---------------------------------------------------------------------
-- 1. Tabelas
-- ---------------------------------------------------------------------

-- Usuários do CRM. Uma linha aqui é o "convite": só quem tem e-mail nesta
-- tabela (com ativo = true) consegue criar senha e entrar.
-- auth_id liga a linha ao usuário do Supabase Auth (auth.users) e é
-- preenchido automaticamente no primeiro acesso.
create table if not exists public.usuarios (
  id        uuid primary key default gen_random_uuid(),
  auth_id   uuid unique,
  nome      text not null,
  email     text,                                   -- pode ser null até o admin preencher
  papel     text not null default 'vendedor',
  ativo     boolean not null default true,
  criado_em timestamptz not null default now(),
  constraint usuarios_papel_check check (papel in ('admin', 'vendedor'))
);

-- E-mail único (ignorando maiúsculas) apenas quando não for nulo.
create unique index if not exists usuarios_email_unico
  on public.usuarios (lower(email))
  where email is not null;

-- Contatos (funil de vendas). id é text gerado pelo app (crypto.randomUUID()).
create table if not exists public.contatos (
  id            text primary key,
  nome          text not null,
  empresa       text not null default '',
  data          date not null default current_date,  -- data do último contato
  status        text not null default 'novo',
  objetivo      text not null default '',
  criado_em     timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint contatos_status_check
    check (status in ('novo', 'conversa', 'degustacao', 'proposta', 'fechado', 'perdido'))
);

-- Produtos (cardápio). Os 7 do site usam ids fixos "site-*"; os demais uuid.
create table if not exists public.produtos (
  id        text primary key,
  nome      text not null,
  categoria text not null default '',
  selo      text not null default '',
  preco     numeric(10,2),                           -- null = "a combinar"
  descricao text not null default '',
  ativo     boolean not null default true,
  do_site   boolean not null default false
);

-- Pedidos. numero é gerado pelo banco (identity) — o app manda numero
-- ausente/null ao criar. Excluir o contato exclui seus pedidos (cascade).
create table if not exists public.pedidos (
  id         text primary key,
  numero     bigint generated by default as identity,
  contato_id text not null references public.contatos (id) on delete cascade,
  data       date not null default current_date,
  entrega    date,                                   -- null = sem data de entrega
  status     text not null default 'orcamento',
  obs        text not null default '',
  criado_em  timestamptz not null default now(),
  constraint pedidos_numero_unico unique (numero),
  constraint pedidos_status_check
    check (status in ('orcamento', 'confirmado', 'producao', 'pronto', 'entregue', 'cancelado'))
);

-- Itens de pedido. Excluir o pedido exclui os itens (cascade); um produto
-- que está em algum pedido NÃO pode ser excluído (restrict).
create table if not exists public.pedido_itens (
  id         text primary key,
  pedido_id  text not null references public.pedidos  (id) on delete cascade,
  produto_id text not null references public.produtos (id) on delete restrict,
  qtd        numeric(10,2) not null default 1,
  preco      numeric(10,2) not null default 0,
  constraint pedido_itens_qtd_check   check (qtd >= 0),
  constraint pedido_itens_preco_check check (preco >= 0)
);

create index if not exists pedidos_contato_idx     on public.pedidos (contato_id);
create index if not exists pedido_itens_pedido_idx on public.pedido_itens (pedido_id);


-- ---------------------------------------------------------------------
-- 2. Triggers auxiliares
-- ---------------------------------------------------------------------

-- contatos.atualizado_em recebe now() a cada update.
create or replace function public.marcar_atualizado_em()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em := now();
  return new;
end;
$$;

drop trigger if exists contatos_atualizado_em on public.contatos;
create trigger contatos_atualizado_em
  before update on public.contatos
  for each row execute function public.marcar_atualizado_em();

-- Antes de gravar um usuário: normaliza o e-mail (minúsculas, sem espaços,
-- '' vira null) e, se já existir uma conta no Auth com esse e-mail,
-- preenche auth_id (útil quando o admin recadastra alguém).
create or replace function public.preparar_usuario()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.email := nullif(lower(btrim(coalesce(new.email, ''))), '');
  if new.auth_id is null and new.email is not null then
    select u.id into new.auth_id
      from auth.users u
     where lower(u.email) = new.email
     limit 1;
  end if;
  return new;
end;
$$;

drop trigger if exists usuarios_preparar on public.usuarios;
create trigger usuarios_preparar
  before insert or update on public.usuarios
  for each row execute function public.preparar_usuario();


-- ---------------------------------------------------------------------
-- 3. Funções de identidade (usadas pelo RLS)
-- ---------------------------------------------------------------------
-- security definer: rodam com os privilégios do dono (postgres) e por isso
-- enxergam a tabela usuarios mesmo com RLS ligado — sem recursão de política.

-- Linha de usuarios do usuário logado. Casa por auth_id; como reserva,
-- por e-mail (caso auth_id ainda esteja null).
create or replace function public.usuario_atual()
returns public.usuarios
language sql
stable
security definer
set search_path = public
as $$
  select u.*
    from public.usuarios u
   where u.auth_id = auth.uid()
      or (u.auth_id is null
          and u.email is not null
          and u.email = lower(coalesce(auth.jwt() ->> 'email', '')))
   order by (u.auth_id = auth.uid()) desc nulls last
   limit 1;
$$;

-- true se o usuário logado existe em usuarios e está ativo.
create or replace function public.usuario_ativo()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select u.ativo from public.usuario_atual() u), false);
$$;

-- true se o usuário logado é admin ativo.
create or replace function public.eh_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select u.ativo and u.papel = 'admin' from public.usuario_atual() u), false);
$$;


-- ---------------------------------------------------------------------
-- 4. Cadastro restrito (triggers em auth.users)
-- ---------------------------------------------------------------------

-- BEFORE INSERT: recusa qualquer signUp (ou "Add user" no painel) cujo
-- e-mail não esteja em usuarios com ativo = true.
create or replace function public.bloquear_cadastro_nao_autorizado()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
      from public.usuarios u
     where u.ativo
       and u.email is not null
       and u.email = lower(btrim(coalesce(new.email, '')))
  ) then
    raise exception 'E-mail não cadastrado. Peça para um administrador incluir você na aba Usuários.';
  end if;
  return new;
end;
$$;

drop trigger if exists mrbrown_bloquear_cadastro on auth.users;
create trigger mrbrown_bloquear_cadastro
  before insert on auth.users
  for each row execute function public.bloquear_cadastro_nao_autorizado();

-- AFTER INSERT: grava usuarios.auth_id = id do novo usuário do Auth.
create or replace function public.vincular_auth_usuario()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.usuarios
     set auth_id = new.id
   where auth_id is null
     and email is not null
     and email = lower(btrim(coalesce(new.email, '')));
  return new;
end;
$$;

drop trigger if exists mrbrown_vincular_usuario on auth.users;
create trigger mrbrown_vincular_usuario
  after insert on auth.users
  for each row execute function public.vincular_auth_usuario();


-- ---------------------------------------------------------------------
-- 5. RLS — segurança por linha
-- ---------------------------------------------------------------------
-- Regra: qualquer usuário autenticado E ativo lê/escreve contatos,
-- produtos, pedidos e pedido_itens. Em usuarios todos leem (e cada um
-- sempre enxerga a própria linha, mesmo desativado, para receber a
-- mensagem certa); só admin insere/atualiza/exclui.

alter table public.usuarios     enable row level security;
alter table public.contatos     enable row level security;
alter table public.produtos     enable row level security;
alter table public.pedidos      enable row level security;
alter table public.pedido_itens enable row level security;

-- contatos
drop policy if exists contatos_acesso on public.contatos;
create policy contatos_acesso on public.contatos
  for all to authenticated
  using (public.usuario_ativo())
  with check (public.usuario_ativo());

-- produtos
drop policy if exists produtos_acesso on public.produtos;
create policy produtos_acesso on public.produtos
  for all to authenticated
  using (public.usuario_ativo())
  with check (public.usuario_ativo());

-- pedidos
drop policy if exists pedidos_acesso on public.pedidos;
create policy pedidos_acesso on public.pedidos
  for all to authenticated
  using (public.usuario_ativo())
  with check (public.usuario_ativo());

-- pedido_itens
drop policy if exists pedido_itens_acesso on public.pedido_itens;
create policy pedido_itens_acesso on public.pedido_itens
  for all to authenticated
  using (public.usuario_ativo())
  with check (public.usuario_ativo());

-- usuarios: leitura
drop policy if exists usuarios_leitura on public.usuarios;
create policy usuarios_leitura on public.usuarios
  for select to authenticated
  using (
    public.usuario_ativo()
    or auth_id = auth.uid()
    or (auth_id is null and email is not null
        and email = lower(coalesce(auth.jwt() ->> 'email', '')))
  );

-- usuarios: escrita só para admin
drop policy if exists usuarios_insercao on public.usuarios;
create policy usuarios_insercao on public.usuarios
  for insert to authenticated
  with check (public.eh_admin());

drop policy if exists usuarios_atualizacao on public.usuarios;
create policy usuarios_atualizacao on public.usuarios
  for update to authenticated
  using (public.eh_admin())
  with check (public.eh_admin());

drop policy if exists usuarios_exclusao on public.usuarios;
create policy usuarios_exclusao on public.usuarios
  for delete to authenticated
  using (public.eh_admin());


-- ---------------------------------------------------------------------
-- 6. Permissões (grants)
-- ---------------------------------------------------------------------
-- O Supabase normalmente já concede isso via default privileges, mas
-- deixamos explícito. "anon" (não logado) não recebe nada nas tabelas:
-- toda leitura/escrita exige login.
grant usage on schema public to anon, authenticated;

grant select, insert, update, delete
  on public.usuarios, public.contatos, public.produtos, public.pedidos, public.pedido_itens
  to authenticated;

grant usage, select on all sequences in schema public to authenticated;

grant execute on function public.usuario_atual(), public.usuario_ativo(), public.eh_admin()
  to authenticated;

revoke all on public.usuarios, public.contatos, public.produtos, public.pedidos, public.pedido_itens
  from anon;


-- ---------------------------------------------------------------------
-- 7. Realtime
-- ---------------------------------------------------------------------
-- Adiciona as 5 tabelas à publicação supabase_realtime (sem duplicar).
-- O app assina postgres_changes e recarrega tudo quando algo muda.
do $$
declare
  tabela text;
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    create publication supabase_realtime;
  end if;

  foreach tabela in array array['contatos', 'produtos', 'pedidos', 'pedido_itens', 'usuarios'] loop
    if not exists (
      select 1
        from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename = tabela
    ) then
      execute format('alter publication supabase_realtime add table public.%I', tabela);
    end if;
  end loop;
end;
$$;


-- ---------------------------------------------------------------------
-- 8. Seed
-- ---------------------------------------------------------------------

-- Usuários iniciais (ids fixos para o script ser reexecutável).
-- Daniela e Guilherme ficam sem e-mail até o admin preencher na aba Usuários.
insert into public.usuarios (id, nome, email, papel, ativo) values
  ('00000000-0000-4000-8000-000000000001', 'Henrique Izzo',            'henriqueia1923@gmail.com', 'admin',    true),
  ('00000000-0000-4000-8000-000000000002', 'Daniela Guastella Izzo',   null,                       'admin',    true),
  ('00000000-0000-4000-8000-000000000003', 'Guilherme Guastella Izzo', null,                       'vendedor', true)
on conflict do nothing;

-- Os 7 produtos do site (preço null = "a combinar"; o admin define depois).
insert into public.produtos (id, nome, categoria, selo, preco, descricao, ativo, do_site) values
  ('site-tradicional', 'Tradicional',          'Cookie tradicional', 'Carro-chefe',       null, 'Massa amanteigada no ponto certo com gotas de chocolate. O queridinho da casa.',                                       true, true),
  ('site-nutella',     'Nutella',              'Cookie recheado',    'Mais pedido',       null, 'Cookie recheado com Nutella cremosa no centro. Servido morno, é puro conforto.',                                       true, true),
  ('site-ovomaltine',  'Ovomaltine',           'Cookie recheado',    '',                  null, 'Recheio cremoso de Ovomaltine com aqueles flocos crocantes. Pura nostalgia.',                                          true, true),
  ('site-chocolatudo', 'Chocolatudo',          'Cookie recheado',    '',                  null, 'Para os chocólatras: massa de chocolate com recheio de chocolate que escorre.',                                        true, true),
  ('site-limao',       'Limão Siciliano',      'Cookie recheado',    '',                  null, 'Recheio cremoso de limão siciliano. Doçura na medida com um toque cítrico refrescante.',                               true, true),
  ('site-pistache',    'Pistache',             'Cookie recheado',    'Especial',          null, 'Recheio cremoso de pistache de verdade. Sofisticado e viciante.',                                                      true, true),
  ('site-mini',        'Mini Cookie Recheado', 'Mini cookies',       'Para compartilhar', null, 'Caixinha de mini cookies recheados para mergulhar na cobertura de chocolate. Perfeitos para compartilhar (ou não!).',  true, true)
on conflict (id) do nothing;

-- Fim. Depois de rodar, confira em Table Editor → usuarios se as 3 linhas
-- existem e em Authentication → Providers → Email se "Confirm email" está
-- do jeito que você quer (desmarcado = login imediato após criar a senha).
